buku-buku/notiyou

- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcworkspace/contents.xcworkspacedata
- lib/main.dart
- lib/models/mission.dart
- lib/screens/config_page.dart
- lib/screens/home_page.dart
- lib/services/mission_service.dart
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile
- pubspec.lock
- pubspec.yaml
(코드는 cursor ai 프롬프팅을 통해 작성되었습니다)
- 개발환경에서 db 역할을 대신 수행할 shared_preferences 추가 (기기 로컬 스토리지 개념인듯)
- 패키지 설치
- Mission 모델 / MissionService 클래스 추가 및 비즈니스 로직 작성
- 미션 시간 설정, 성공 여부 등을 스토리지에 저장하여 개별환경에서도 미션정보가 유지되도록
- 매일 자정이 지나면 새로운 미션 추가 (기존 미션도 저장)
- Home 화면 기능 및 ui 구현
- 체크박스 체크 시 미션 수행. 해제 시 취소
- 미션시간이 지났는데 수행이 안 된 경우 경고 메시지 표기
- 미션이 완료된 경우 완료 시간 표기
- showTimePicker를 사용하여 미션시간 input에서 시간을 설정할 수 있도록 변경
Commits on Nov 1, 2024
- [chore: 로컬 스토리지 활용을 위한 shared_preferences 추가](https://github.com/buku-buku/notiyou/pull/1/commits/fb2ce525110ec215252225501b8b61a72dbd4100)
Commits on Nov 2, 2024
- [feat: showTimePicker를 사용하여 미션 시간 선택가능하도록 수정](https://github.com/buku-buku/notiyou/pull/1/commits/6baa9691bcabecd0c58bef00b7b5d8f18159dddf)
- [feat: MissionService 클래스 …
> [feature] 스토리지를 사용하여 미션 정보 저장. 미션 기능 구현

- lib/repositories/mission_repository.dart
- lib/services/mission_service.dart
향후에 미션 데이터는 클라이언트에서뿐 아니라 서버상에서 다루어지게 될 데이터이기도 하다보니,
이후 복잡해질 수 있는 가능성을 염두하여 미션 데이터를 다루는 로직을 별도 클래스로 분리해두려고 합니다.
- [ca2d66e](https://github.com/buku-buku/notiyou/pull/3/commits/ca2d66e7506c21deb7dbd3ee39ed95e4becaa945) 기존의 mission_service에서 미션 데이터를 다루는 로직들을 추출하여 mission_repository 클래스를 작성하였습니다.
- [e70706e](https://github.com/buku-buku/notiyou/pull/3/commits/e70706ead9c5ea837d3720748682bc929ce7c23e) 모든 미션 데이터 삭제 메서드를 mission_repository에 추가하였습니다.
- [75c8936](https://github.com/buku-buku/notiyou/pull/3/commits/75c8936bbc13493d06d6218fecfa932f6a57a094) 미션 데이터에 접근하기 위한 키를 레포지토리내에서 캡슐화하여 관리하도록 하고, 관련된 모든 메서드를 DateTime 객체를 인자로 전달받는 형식으로 변경하였습니다.
- 미션이 설정되어 있는 상황으로 가정하였을때, 미션 시간을 변경할때 오늘의 미션 시간도 변경할지 말지를 유저에게 선택권을 주는게 좋을것 같습니다. 이를 위한 개발을 진행할 예정입니다.
- 미션에 대한 완료 여부 기록도 mission_repository에서 관리하는편이 좋을것 …
> [refactor] mission_service에서 미션 데이터를 다루는 로직을 별도 클래스로 추출

- lib/models/mission.dart
- lib/repositories/mission_repository.dart
- lib/screens/config_page.dart
- lib/screens/home_page.dart
- lib/services/mission_service.dart
- lib/utils/time_utils.dart
이후 미션 데이터는 서버상에서 생성되어 관리될 예정입니다. 
다만 인터넷 연결 불안정 문제 및 서버 미개발 상황인 점을 고려해서 로컬 데이터 관리를 유지할 계획입니다. 로컬 데이터의 경우에는 오늘의 미션을 제외하고는 불필요하기 때문에, 오늘을 제외한 로컬 상의 미션 데이터를 모두 제거하도록 개발합니다.
*지금 다시 보니 기존에도 미션 데이터를 제거하는 처리가 되어 있는것 같네요 ㅎ.. 그냥 로직만 좀 정리했다 정도로 이해해주시면 좋을것 같습니다.
- [3c3a2b8](https://github.com/buku-buku/notiyou/pull/4/commits/3c3a2b801406a8dbc64a2e795a909439f36e9fa0) "미션 시간"에 대한 데이터 관리 또한 mission_repository에서 관리하도록 변경합니다. 
- [1beaac6](https://github.com/buku-buku/notiyou/pull/4/commits/1beaac68af58ebc23bce2d0217e61b12c16e281b) mission_repository에서 미션 데이터를 변경하는 추가적인 메서드들을 작성하여, mission_service의 코드를 개선합니다.
- [4d1be2d](https://github.com/buku-buku/notiyou/pull/4/commits/4d1be2dbad1431a531c2901da00e6e9f48372394) mission_service에서 shared preferences에 대한 의존성을 제거합니다.
- …
> [feature] 앱 실행시 오늘을 제외한 로컬상의 미션 데이터를 모두 제거하도록 처리

- lib/models/mission.dart
- lib/repositories/mission_repository.dart
- lib/screens/config_page.dart
- lib/screens/home_page.dart
- lib/services/mission_service.dart
https://github.com/buku-buku/notiyou/pull/1#discussion_r1827859770 에서의 논의 내용을 바탕으로 작업이 진행되었습니다.
설정 화면에서 "미션 시간"을 변경하였을때 오늘의 미션은 이에 반영되지 않는 상황이 있습니다.
시나리오에 따라 이것이 자연스러운 경우도, 자연스럽지 않은경우도 있는것 같아서, "미션 시간"을 변경하였을때 오늘의 미션에도 이를 반영할지 여부를 묻고, 이에 따라 적절한 처리를 해주도록 개발을 진행하였습니다.
- [b29a09b](https://github.com/buku-buku/notiyou/pull/5/commits/b29a09b0aa9a45eeeae5ee85f1ea7727db35a585) 미션 리스트를 조회할때 조회되는 미션이 없을 경우 오늘의 미션 데이터를 생성하는 처리를 레포지토리로 이동했습니다. 해당 로직은 서버가 생김에 따라 제거될 확률이 높을것 같네요. (서버에서 미션 생성을 실패했을 경우를 고려해서 살려둘수도..)
- [b968ef1](https://github.com/buku-buku/notiyou/pull/5/commits/b968ef1054543234e1f255283c593f3619fafebb) "미션의 생성은 서버에서 처리한다."라는 취지에 맞게 mission_repository에서 미션을 직접적으로 생성하는 `setMissions()` 메서드를 `_setMissions()`로 캡슐화합니다. 
- [076cff8](https://github.com/buku-buku/notiyou/pull/5/commits/076cff87 …
> [feature] 미션 시간을 변경할때 오늘의 미션도 업데이트 할지 여부를 묻고, 이에 맞게 처리하도록 변경

- lib/repositories/mission_repository.dart
- lib/repositories/mission_time_repository.dart
- lib/services/mission_service.dart
작업을 진행하다보니 mission_repository가 지나치게 뚱뚱해지고 있는 느낌이 들어서, "미션 시간" 관리와 "미션" 관리를 분리하려고 합니다.
- [6886852](https://github.com/buku-buku/notiyou/pull/6/commits/688685242c1b8cb9bb3d63d2cf75df5376774a86) 미션 시간 데이터를 관리하는 mission_time_repository를 작성합니다.
- [f730c51](https://github.com/buku-buku/notiyou/pull/6/commits/f730c5112908e42501a4608088469b8c214657ca) 각 레포지토리에 대한 주석 설명을 추가합니다.
> [refactor] 미션 시간을 관리하는 mission_time_repository 작성

- lib/repositories/notification_template_repository.dart
- lib/services/notification_template_service.dart
미션 성공 또는 실패시 발송하게 될 메시지를 조회하고, 변경하는 기능을 제공하는 서비스 클래스를 작성합니다.
- [implement: 미션 노티 템플릿 데이터를 관리하는 notification-template_repository 작성](https://github.com/buku-buku/notiyou/pull/9/commits/fc672093460c6674f9a0bf9ca13873622c6f2c22)
- [implement: 미션 노티 메시지 템플릿에 관한 기능을 제공하는 notification_template_service 작성](https://github.com/buku-buku/notiyou/pull/9/commits/8d2e9501fdbff09339979f401b6f113279d91c86)
- 서비스 클래스는 테스트코드를 작성해두면 참 좋겠는 지점인것 같은데, repository에 대해서 의존성 주입이 가능하도록 짜여져있지 않다보니까 테스트 코드를 작성하는게 상당히 번거로운것 같더라구요. 거기다 static class처럼 구현이 되어있다보니 의존성 주입이 가능하게끔 하려면 static class를 사용하지 않게끔 다시 고쳐 구현해야할것 같습니다.
- 약간 Flutter에는 DI Container와 같은게 존재할지 알아보고 싶은 맘이 뿜뿜한 상태..
이상 테스트 코드를 결국 작성하지 않은것에 대한 변명이었습니다 ㅎㅎ
- 이를 활용하여 #10 에서 설정 페이지에 템플릿 수정 기능을 구현하였습니다.
> [feature] 미션 노티 메시지 템플릿 관련 기능을 제공하는 notification_template_service 작성

- ios/Podfile.lock
kakao_flutter_sdk_common 등 ios 환경에서 앱에 필요한 의존성을 lock 파일에 업데이트합니다.
(현재 메인 브랜치 2fac56f 기준)
ios 환경에서 필요한 앱의 의존성은 어느 시점 이후로 업데이트된 내용이 git에 포함되지 않았던 것 같아요. 
현재 모든 팀원이 메인 브랜치를 받아와서 ios 환경으로 빌드하면 항상 동일한 diff가 생길거라서 이 PR에서 업데이트합니다.
> [NY-42] ios/Podfile.lock 업데이트

- .vscode/settings.json
- lib/screens/login_page.dart
- lib/screens/splash_page.dart
- lib/services/auth/auth_service.dart
- lib/services/auth/kakao_auth_service.dart
- lib/services/auth/supabase_auth_service.dart
- lib/services/supabase_service.dart
kakao SDK를 통해 OAuth 인증을 수행하고, 이를 supabase 유저 테이블에 등록하도록 구현하였습니다.
*인증의 플로우를 그림으로 표현해보았습니다.
- [feat: supabase 카카오 로그인 연동](https://github.com/buku-buku/notiyou/pull/25/commits/9650a94cb7a8d2037598a37961ed3fba9a30d351)
- `New` auth_service.dart, kakao_auth_service.dart, supabase_auth_service.dart
기존의 인증 처리를 하는데 있어서 kakao <-> supabase 간의 연동으로 인한 복잡도가 생김에 따라, 기존 login_page와 splash_page에 구현되어 있었던 비즈니스 로직을 auth_service 클래스로 추출하였습니다. 또한, kakao와 supabase에 대한 로직을 분리하여 관리하기 위해 kakao_auth_service, supabase_auth_service 라는 클래스로 분리하여 관리하도록 했습니다. 
- 코드 구현 이외에 설정한 과정 기록을 [노션 페이지](https://www.notion.so/SDK-Supabase-bb9db4247879435eba97cdf9dbab05a7?pvs=4)에 정리해 두었습니다.
플랫폼 별 테스트
해당 브랜치에서 앱을 실행하여, 각자의 카카오 로그인을 수행하고, [supabase의 auth 테이블](https://supabase.com/dashboard/project/pmiivbdkefsnzznxghwb/auth/users)에 잘 …
> [NY-38] feat: supabase 카카오 로그인 연동

- android/app/src/main/AndroidManifest.xml
- lib/fixtures/mission_history.dart
- lib/main.dart
- lib/models/mission_history.dart
- lib/screens/history_page.dart
- lib/services/mission_history_service.dart
- lib/utils/time_utils.dart
- lib/widgets/mission_history_list_item.dart
- pubspec.lock
- pubspec.yaml
사용자는 히스토리 페이지에 들어가면 미션 기록 목록을 볼 수 있습니다. (Supabase와의 기능 연동은 되어 있지 않고 UI만 추가한 변경)
> [!Warning]
>
> 개발 편의를 위해 미션 기록은 더미 데이터를 fixture로 넣어서 보여줍니다. 따라서 현재 PR에서는 홈에서 미션을 체크해도 히스토리 페이지에 반영되지 않습니다.
- [chore: android 워닝 제거](https://github.com/buku-buku/notiyou/pull/27/commits/c9b0736b77aca577c09a0cc9739aba90e96e7372)
- [chore: 한국 local 시간 계산을 위해 Intl 패키지 추가](https://github.com/buku-buku/notiyou/pull/27/commits/9d417a1733a4229d8361138488d4897333a75aad)
- [chore: MissionHistory 모델 및 fixture 추가](https://github.com/buku-buku/notiyou/pull/27/commits/2d180c84bc626fec46ece8948176175227957c64)
- [feat: HistoryPage에서 MissionHistory 목록 렌더링](https://github.com/buku-buku/notiyou/pull/27/commits/5a392e34c70a3e2d49e7ecb8d9e344783f7c2a8f)
- [feat: history_page에서 MissionHistoryService와 소통하도록 …
> [NY-14] 히스토리 페이지에 미션 기록 목록 추가

- lib/routes/index.dart
- lib/services/auth/kakao_auth_service.dart
- lib/services/auth/supabase_auth_service.dart
로그아웃이 동작하지 않는 문제를 수정합니다.
- [fix: 로그아웃이 동작하지 않는 문제 수정](https://github.com/buku-buku/notiyou/pull/30/commits/14b6c08c5e7415b9f7db88a19d104507fb20f7ab)
- [fix: SupabaseAuthService.getUser가 유저정보를 로컬 데이터로 조회해오도록 수정](https://github.com/buku-buku/notiyou/pull/30/commits/41f1a882b66d4dbdf938937b830a721103222d83)
-  이따금씩 remote에서 유저정보를 불러오지 못하는 경우가 있는데, 이때 에러를 던지지 않고 무한으로 함수 호출이 resolve 되지 않더라구요. 그래서 그냥 로컬상에 저장해둔 유저정보를 반환하는 것으로 바꿨습니다.
> [NY-64] 로그아웃이 동작하지 않는 문제 수정

- lib/repositories/mission_repository.dart
- lib/repositories/mission_time_repository_interface.dart
- lib/repositories/mission_time_repository_local.dart
- lib/repositories/mission_time_repository_remote.dart
- lib/screens/config_page.dart
- lib/services/mission_service.dart
- lib/services/push_alarm_service.dart
- lib/services/supabase_service.dart
- pubspec.lock
- pubspec.yaml
- test/screens/signup_page_test.dart
기존의 로컬 저장소를 이용하여 미션 시간 정보를 관리하던 mission_time_repository의 remote용을 작성하여 기존 사용처 코드를 대체합니다.
- 서비스레이어의 비즈니스 로직에 영향을 주지 않기 위해 mission_time_repository의 인터페이스를 정의하여 사용했습니다.
- 정의된 인터페이스를 활용하기 위해서, 기존에 static으로 정의되어 있던 메서드 및 프로퍼티들을 모두 인스턴스 프로퍼티, 메서드로 전환하고, `싱글턴 패턴`의 클래스로 변경하였습니다.
- [feat: supabase의 미션테이블을 사용하는 mission_time_respository_remote 작성 및 기존 코드 교체](https://github.com/buku-buku/notiyou/pull/29/commits/a91213bb5a3d2ac7c67cf6f235d4fecc64f543ad)
- [test: 테스트를 위한 메서드 작성 및 테스트코드에 적용](https://github.com/buku-buku/notiyou/pull/29/commits/5d383f774d94c51e4a9f8e7d8dfab8c5970483be)
- [missions 테이블](https://supabase.com/dashboard/project/pmiivbdkefsnzznxghwb/editor/40376?schema=public)을 생성하였습니다.
- [Row Level Security](https://supabase.com/docs/guides/database/postgres/row-level-security) 정책 설정을 통해, …
> [NY-39] mission_time_repository Supabase 연동하기

- lib/models/mission.dart
- test/models/mission_test.dart
홈 페이지에서 사용자가 미션을 체크했다가 다시 해제하면 completedAt이 null로 변경되어야 하는데 이전 completedAt 값이 남아 있는 문제를 해결합니다.
- [fix: mission.copyWith에서 completedAt이 null로 업데이트 되지 않는 버그 해결](https://github.com/buku-buku/notiyou/pull/33/commits/25177482fea02c0ff52ca6bdcbbf3b269be7e67a)
- [spec: mission.copyWith에서 isCompleted=false이면 completedAt=null 테스트](https://github.com/buku-buku/notiyou/pull/33/commits/37157a43529e1f1043d0c2c658f4735ae7cb1e37)
> 정상 동작 화면:
> [NY-69] mission.copyWith에서 completedAt이 null로 업데이트 되지 않는 버그 해결

- lib/models/mission.dart
- lib/repositories/mission_repository_remote.dart
mission_id를 통해 mission table에 접근하여 mission_at 값을 가져오고 있다.
- (Cons) 무조건 최신으로 설정된 시간으로 동기화되어 관리된다.
- (Cons) 이후 이전 미션 내역들을 조회시, 그 시점에 설정된 미션 시간이 아닌, 최신에 설정된 미션 시간으로 조회된다.
mission_history 테이블에 mission_at 필드를 추가하고, missions 테이블과는 별도로 관리한다.
- (Pros) 무조건 최신 설정된 시간으로 동기화되지 않아도 된다. 정책에 따라 선택 가능
- (Pros) 이전 미션 내역들을 조회할때, 그 시점에 설정된 미션 시간을 조회할 수 있다.
- supabase mission_history 테이블에 mission_at 컬럼 추가
- [feat: mission_history 테이블에서 mission_at 필드 관리되도록 변경](https://github.com/buku-buku/notiyou/pull/36/commits/fde375f302f92996fd64157caac9798c8a3b3ad3)
- mission_number 컬럼을 제거하고, 관련 로직들을 mission_id를 활용하는 방식으로 대체하려고 합니다.
- mission_number 컬럼이 있고, 이를 통해 미션을 검색하는 방식은 기능의 복잡도를 높이게 될것 같다는 생각이 많이 듭니다. mission_number 컬럼이 없더라도 mission_id를 통해 충분히 기존의 기능들을 제공할 수 있고, 로직의 복잡도도 줄일수 있을것 같다는 생각이 들어.
> [NY-70] mission_history 테이블에서 mission_at 필드 관리되도록 변경

- android/app/src/main/AndroidManifest.xml
- lib/main.dart
- lib/services/local_notification_service.dart
- lib/services/mission_alarm_service.dart
- lib/services/mission_service.dart
- lib/services/push_alarm_service.dart
안드로이드에서 notification이 정상 동작하도록 해결합니다. 
(트러블슈팅 과정에서 PushAlarmService 코드가 여러 로직(`MissionRepsitory` + `FlutterLocalNotificationsPlugin`)이 섞여 있어서 조작하는 게 쉽지 않아서 두 로직을 분리하는 리팩터링도 같이 진행했습니다.
- [feat: full-screen intent notifications](https://github.com/buku-buku/notiyou/pull/38/commits/53c5b2dff5d9af39b11749b9b8635adc30ca9ce2)
- [feat: LocalNotificationService 추가](https://github.com/buku-buku/notiyou/pull/38/commits/6ec349a31a47ecc6cb1355182b3fa5c346f5a1cd)
- [fix: 에러 해결을 위해 안드로이드 intent xml 수정](https://github.com/buku-buku/notiyou/pull/38/commits/e17081edc78f7ad0382933db6653d066a7f1fc02)
- [fix: android에서 scheduled notification 받을 수 있도록 xml 수정](https://github.com/buku-buku/notiyou/pull/38/commits/48bedc8d51853d9071977d6181fdd0f4bfd8cce2)
- [refactor: PushAlarmService가 LocalNotificationService …
> [NY-62] 안드로이드 notification 에러 해결 및 PushAlarmService 리팩토링

- .vscode/settings.json
- analysis_options.yaml
- lib/fixtures/mission_history.dart
- lib/layouts/back_button_layout.dart
- lib/layouts/bottom_nav_layout.dart
- lib/main.dart
- lib/models/mission.dart
- lib/repositories/mission_repository_interface.dart
- lib/repositories/mission_repository_local.dart
- lib/repositories/mission_time_repository_local.dart
- lib/repositories/mission_time_repository_remote.dart
- lib/repositories/supporter_repository.dart
- lib/routes/index.dart
- lib/routes/router.dart
- lib/screens/config_page.dart
- lib/screens/history_page.dart
- lib/screens/home_page.dart
- lib/screens/login_page.dart
- lib/screens/signup_page.dart
- lib/screens/splash_page.dart
- lib/services/mission_alarm_service.dart
- lib/services/mission_history_service.dart
- lib/services/mission_service.dart
- lib/services/notification_template_service.dart
- lib/services/supporter_service.dart
- lib/widgets/mission_history_list_item.dart
- lib/widgets/notification_template_config.dart
- lib/widgets/supporter_section.dart
프로젝트 내부 모듈을 절대 경로로 import 하도록 통일하는 린트 룰을 추가합니다
- [chore: lint always use package imports](https://github.com/buku-buku/notiyou/pull/32/commits/04e15ea91d488c40d0a17c0d512de31990905e12)
- [chore: 저장하면 자동 fix 되도록 vscode 설정 추가](https://github.com/buku-buku/notiyou/pull/32/commits/f0f94b9c3de421b99de7d01b51457231699edfcb)
- [lint: 절대 경로 lint rule 적용](https://github.com/buku-buku/notiyou/pull/32/commits/bb95529cf79f7dab3c31ea0e56d6b58a4f0096cc)
- PR 충돌을 최소화하기 위해 다음과 같이 진행합니다
- 다 같이 모여서 기존에 올라온 PR을 모두 머지한다
- 해당 PR의 브랜치에서 아래 명령어를 실행해서 린트 fix를 진행한다
- 해당 PR을 머지한다
```sh
dart fix --apply
```
- https://stackoverflow.com/questions/61708945/how-to-fix-auto-fixable-problems-on-vscode-with-flutter
> [NY-67] 절대 경로 import 린트 룰 추가

- lib/main.dart
- lib/models/mission.dart
- lib/repositories/mission_history_repository_interface.dart
- lib/repositories/mission_history_repository_local.dart
- lib/repositories/mission_history_repository_remote.dart
- lib/repositories/mission_time_repository_remote.dart
- lib/screens/config_page.dart
- lib/screens/home_page.dart
- lib/services/mission_config_service.dart
- lib/services/mission_history_service.dart
- lib/services/mission_service.dart
mission_service 클래스와 관련하여 명칭, 책임과 관련한 개선 작업을 민철님과 함께 진행하였습니다.
- [refactor: supabase의 테이블 missions -> challenger_mission_time 변경 사항 대응](https://github.com/buku-buku/notiyou/pull/39/commits/0dbce71feb2511f9c8330b767f607a737b0926ee)
- [refactor: mission_repository -> mission_history_repository로 명칭 변경](https://github.com/buku-buku/notiyou/pull/39/commits/933e9127d5da33526b5d04a34fbf28c49268ccd4)
- [refactor: mission_service -> mission_config_service로 변경하고 일부 메서드를 mission_history_service로 이동](https://github.com/buku-buku/notiyou/pull/39/commits/7d17ea6b09aa03aeda4d11d6768b1cca4df8dc65)
- Supabase Table 수정
- https://supabase.com/dashboard/project/pmiivbdkefsnzznxghwb/editor/40376?schema=public
> [NY-72] mission_service 클래스의 책임 분리 및 미션 관련 레포지토리 개선

- android/app/src/main/AndroidManifest.xml
- lib/widgets/supporter_section.dart
- 임시 웹페이지 vercel 배포
- 도메인: https://temp-web-link.vercel.app/
- 레포지토리: https://github.com/42KIM/temp-web-link
- 카카오톡 공유하기를 사용하여 조력자에게 초대링크를 전송하고,
- 앱이 설치된 경우 App Link/Universal Link 처리 흐름 진행
- 앱이 설치되지 않은 경우 temp-web-link를 거쳐 play store로 redirect (현재는 노티유가 스토어에 없기때문에 스토어 메인으로 연결)
- App Link / Universal Link 처리를 위한 임시 웹도메인 주소로 초대 링크 발송
- App Links 테스트 방법 By Cursor.ai
```
curl -v https://temp-web-link.vercel.app/.well-known/assetlinks.json
adb shell pm verify-app-links --re-verify com.example.notiyou
adb shell pm get-app-links com.example.notiyou
adb shell am start -W -a android.intent.action.VIEW \
-d "https://temp-web-link.vercel.app/invite/123" \
-c android.intent.category.BROWSABLE
```
- TODO: 임시 웹페이지 assetlinks.json에 사용된 DEBUG용 fingerprint를 release용으로 변경 필요
> [NY-29] 도전자는 조력자를 초대할 수 있다 (안드로이드 App Links만)

- lib/models/mission.dart
- lib/repositories/mission_history_repository/mission_history_repository_remote.dart
1. 미션 설정 변경시 새롭게 설정된 미션으로 업데이트합니다. 
2. 이때 미션 히스토리도 함께 업데이트합니다. 단, 이미 미션 히스토리가 존재할 때만 업데이트하고 미션 히스토리가 존재하지 않으면 새로 생성합니다.
3. 그런데 2번 과정에서 미션 히스토리가 존재하지 않는다고 잘못 판단하여, 미션 히스토리가 계속 생성되는 문제가 발생했습니다.
미션 히스토리 테이블에 missionId가 존재하는지 판단할 때 missionId가 아닌 미션 히스토리의 id로 잘못 비교하고 있었기 때문입니다.
- [fix: 설정 변경하면 미션 히스토리가 계속 생성되는 문제 해결](https://github.com/buku-buku/notiyou/pull/59/commits/148e469af72f50f5442d17242691cd640e7ed02f)
https://github.com/user-attachments/assets/e28b8115-87ed-4a40-8a27-051865237861
https://github.com/user-attachments/assets/dc65ef2e-3246-4e6e-b6f3-41cfa6b837de
> [NY-120] (bug) 설정 변경하면 미션 히스토리가 계속 생성되는 문제 해결

- lib/screens/challenger_config_page.dart
- lib/screens/home_page.dart
- 도전자는 미션 생성을 완료한 이후에만 조력자를 초대할 수 있다
- 도전자는 조력자 초대가 완료되지 않은 경우, 홈 페이지에서 조력자 초대를 요구하는 CTA 버튼을 볼 수 있다
- 도전자는 조력자 초대를 요구하는 CTA 버튼을 클릭하면, 조력자 초대 버튼이 있는 설정 페이지로 이동한다
- 도전자는 조력자 초대가 완료된 경우, 홈 페이지에서 함께 하는 조력자의 정보를 볼 수 있다
- [feat: 설정 페이지에 처음 진입한 경우 서포터 초대 UI를 보여주지 않는다](https://github.com/buku-buku/notiyou/pull/62/commits/561b6cb6d3823ea9923802da9ae1223db7b34a30)
- [feat: 홈 화면에 조력자 초대 완료 여부에 따른 AlertBanner 표시](https://github.com/buku-buku/notiyou/pull/62/commits/5110b2ec19e3a825e705fc3e927ec101201082b9)
- 조력자를 식별할 수 있는 닉네임이나 부가 정보가 꼭 있어야겠어요. 함께 하는 조력자 정보를 uuid로 보여줄 수는 없으니..
- #61 에 이어서 작업한 브랜치입니다.
> 도전자는 미션 생성을 완료한 이후에만 조력자를 초대할 수 있다
> 도전자는 조력자 초대가 완료되지 않은 경우, 홈 페이지에서 조력자 초대를 요구하는 CTA 버튼을 볼 수 있다
> 도전자는 조력자 초대를 요구하는 CTA 버튼을 클릭하면, 조력자 초대 버튼이 있는 설정 페이지로 이동한다 …
> [NY-108/feat] 도전자는 미션 생성을 완료한 이후에만 조력자를 초대할 수 있다

- lib/repositories/mission_history_repository/mission_history_repository_remote.dart
- lib/screens/history_page.dart
- lib/screens/login_page.dart
- 히스토리 페이지 정렬이 이상한 문제를 해결합니다
- 히스토리 페이지에서 보여주는 날짜 포맷을 변경합니다.
- 회원가입시 카톡 프로필 이름을 사용한다는 문구 추가합니다.
- [fix: 히스토리 페이지에서 미션 히스토리 목록을 최신 날짜 기준 정렬](https://github.com/buku-buku/notiyou/pull/86/commits/f9f0e6abeda36a17ef870386adcc5d4520974f82)
- [style: 날짜 포맷을 YYYY.mm.dd로 변경](https://github.com/buku-buku/notiyou/pull/86/commits/3295f7d4f1cd85e2b5559aaa4fe6ae8176d647d3)
- [feat: (NY-147) 회원가입시 카톡 프로필 이름을 사용한다는 문구 추가](https://github.com/buku-buku/notiyou/pull/86/commits/cf2cba3a085e83520d40f8e32fb3ec1735863f0c)
> [NY-155] 무호님과 Pair QA에서 나온 간단한 이슈 해결
